### PR TITLE
Use Option for author and message in rebase_commit

### PR DESCRIPTION
**Pull request by akhilkpdasan**
#390

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! I'm gonna hold off on this for now to batch up breaking changes, but will merge when another major version happens

**Comment by akhilkpdasan** [comment]
It looks like signature is optional in `rebase_finish` as well https://libgit2.org/libgit2/#HEAD/group/rebase/git_rebase_finish

**Comment by alexcrichton** [comment]
👍

**Comment by neithernut** [comment]
FYI: regarding libgit2's `git_rebase_commit()` there are API changes/new capabilities being currently discussed (libgit2/libgit2#4913).

**Comment by alexcrichton** [comment]
Ok we've got breaking changes on master now, so I"m going to merge! Thanks for the PR and sorry for the delay!

**Pull request merged**
