### PR TITLE
Add modifiers for error code and class (#576)

### PR DESCRIPTION
**Pull request by kim**
Arguably the most naive / liberal way to allow for custom errors. There might be reasons to only allow a subset of the error codes / classes, but I can't make up my mind which ones that should be. If that's the case, perhaps a set of specialised constructors would be preferrable, otherwise I'd lean towards amending this to define a `new` constructor which takes the code and class directly.

Aside: I noticed that the `ErrorCode` enum is missing some possible values from the binding. I'll submit that separately.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Could these take `&mut self` though since I think that's more idiomatic?

**Comment by kim** [comment]
> I think that's more idiomatic

I'm seeing "setters" used in a few different flavours across the ecosystem, so I can't tell, really :) `mut Self -> Self`, `&mut self -> &mut Self`, and `&mut self -> ()` all yield very different ergonomics, and I chose the first because I figured that one would mostly want to construct custom errors, not actually modify them. So, what do you think of just `new(class, code, message)` or `custom(...)`?

**Comment by alexcrichton** [comment]
Adding `new` also sounds good to me! Typically with what I've seen `with_x` is `self -> self` while `set_x` is just `&mut self -> ()`. Builder-style `x` is where `&mut self -> &mut self` comes into play

**Comment by alexcrichton** [comment]
Thanks!

**Pull request merged**
