### PR TITLE
examples: replace structopt with clap

### PR DESCRIPTION
**Pull request by tamird**
See https://github.com/TeXitoi/structopt/issues/525.

Currently git2 is the most downloaded dependent of structopt:
https://crates.io/crates/structopt/reverse_dependencies.

### CODE REVIEW

**Comment by tamird** [comment]
@ehuss this is green now that you merged #1008. Could you take a look please?

**Comment by tamird** [comment]
@ehuss friendly ping!

**Comment by tamird** [comment]
@ehuss ping.

**Comment by tamird** [comment]
@epage can you merge it?

**Review by ehuss — APPROVED** [review]
Thanks!

**Comment by tamird** [comment]
Thanks! Would it be possible to cut a point release?

**Comment by ehuss** [comment]
Can you say more about what you are looking for in a new release? I don't expect people are using the examples directly, and it shouldn't have any impact on the git2-rs library.

**Comment by tamird** [comment]
Ah, it's a dev dependencies. My mistake. The only thing a release would do is remove git2-rs from [the rankings](https://crates.io/crates/structopt/reverse_dependencies).

**Pull request merged**
