### PR TITLE
add tag_foreach to repo (#594)

### LINKED ISSUE #594: safe wrapper for `git_tag_foreach`
see https://libgit2.org/libgit2/#HEAD/group/tag/git_tag_foreach

PR coming in

### PR DESCRIPTION
**Pull request by extrawurst**
closes #594

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Should this perhaps yield `&[u8]` instead of `Option<&str>` to make sure we can yield everything?

**Comment by extrawurst** [comment]
@alexcrichton updated

**Comment by alexcrichton** [comment]
Thanks!

**Comment by extrawurst** [comment]
@alexcrichton thank a bunch! As usual I would love to have a release to give it a spin in https://github.com/extrawurst/gitui/issues/206 :)

**Comment by alexcrichton** [comment]
Sure thing, done now!

**Pull request merged**
