### PR TITLE
stash_save2 adds support for optional message

### LINKED ISSUE #565: Repository::stash_save NULL message not supported
`git_stash_save` supports NULL as an optional message and will do internal logic to define a stash name.
see https://libgit2.org/libgit2/#HEAD/group/stash/git_stash_save

`git2-rs` currently does not support this behaviour.

If I were to create a PR how do you guys handle this sort of change? the *correct* api would take message as `Option<&str>` and pass null or the converted cstring. this change would break the API. is that ok?

### PR DESCRIPTION
**Pull request by extrawurst**
closes #565

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Could this update the previous method to call the new one too?

**Comment by extrawurst** [comment]
great idea! incoming

**Comment by extrawurst** [comment]
@alexcrichton done

**Comment by extrawurst** [comment]
@alexcrichton cool, then I only need a release now since cargo does not allow git references as dependencies :)

**Comment by alexcrichton** [comment]
Sure thing, published!

**Comment by extrawurst** [comment]
@alexcrichton thanks! how do we make sure we keep track of this to refactor it in a breaking release?

**Comment by alexcrichton** [comment]
Typically open PRs are left, otherwise it's "I hope this sticks in my brain". Not exactly an infallible system!

**Pull request merged**
